=== shilpa-k29/train_booking-_system/status.xsd
<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Trainticket">
<xs:complexType>
<xs:sequence>

<xs:element name="Trainstatus" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Bookedseats" type="xs:integer"></xs:element>
<xs:element name="Availableseats" type="xs:integer"></xs:element>
<xs:element name="waitingseats" type="xs:integer"></xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

=======
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Trainticket">
<xs:complexType>
<xs:sequence>

<xs:element name="Trainstatus" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="Bookedseats" type="xs:integer"></xs:element>
<xs:element name="Availableseats" type="xs:integer"></xs:element>
<xs:element name="waitingseats" type="xs:integer"></xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>

>>>>>>> 41a41b1086db82e7a1f009edd7010c10a95ac0ab
</xs:schema>

=== shilpa-k29/train_booking-_system/status.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="status.xsl"?>
<Trainticket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="status.xsd">
    
  <Trainstatus>
    <Bookedseats>54</Bookedseats>
    <Availableseats>20</Availableseats>
    <waitingseats>65</waitingseats>
  </Trainstatus>
    <Trainstatus>
    <Bookedseats>43</Bookedseats>
    <Availableseats>56</Availableseats>
    <waitingseats>34</waitingseats>
  </Trainstatus>
    <Trainstatus>
    <Bookedseats>67</Bookedseats>
    <Availableseats>54</Availableseats>
    <waitingseats>21</waitingseats>
  </Trainstatus>
    <Trainstatus>
    <Bookedseats>89</Bookedseats>
    <Availableseats>32</Availableseats>
    <waitingseats>21</waitingseats>
  </Trainstatus>
    <Trainstatus>
    <Bookedseats>90</Bookedseats>
    <Availableseats>12</Availableseats>
    <waitingseats>46</waitingseats>
  </Trainstatus>
  
  
</Trainticket>
