=== shilpa-k29/train_booking-_system/station.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Trainticket">
<xs:complexType>
<xs:sequence>
<xs:element name="station" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>
<xs:element name="stationid" type="xs:string"></xs:element>
<xs:element name="stationname" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:simpleType name="date" >
 <xs:restriction base="xs:string">
 <xs:whiteSpace value="collapse" fixed="true"/>
 </xs:restriction>
</xs:simpleType>
<xs:simpleType name="Time">
    <xs:restriction base="xs:string">
        <xs:pattern value="((0[0-9]|1[0-9]|2[0-3]):[0|3][0]:[0][0])"/>
    </xs:restriction>
</xs:simpleType>
<xs:simpleType name="email">
<xs:restriction base="xs:string"><xs:pattern value="[^@]+@[^\.]+\..+"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="pass">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z0-9]{8}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== shilpa-k29/train_booking-_system/station.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="station.xsl"?>
<Trainticket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="station.xsd">
<station>
    <stationid>1</stationid>
    <stationname>Byndoor</stationname>
  </station>
   <station>
    <stationid>2</stationid>
    <stationname>Yeshwanthpur</stationname>
  </station>
   <station>
    <stationid>3</stationid>
    <stationname>Majestic</stationname>
  </station>
   <station>
    <stationid>4</stationid>
    <stationname>Mysore</stationname>
  </station>
   <station>
    <stationid>5</stationid>
    <stationname>Mumbai</stationname>
  </station>
   <station>
    <stationid>6</stationid>
    <stationname>Delhi</stationname>
  </station>
  </Trainticket>
